name: 直播源验证


on:
  schedule:
    - cron: '1 */8 * * *'        #这里更改自动运行的时间，没这两行的话只能手动运行
  workflow_dispatch:
    分支:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install selenium requests futures eventlet
      - name: Install dependencies
        run: pip install opencv-python requests 
      - name: Install dependencies
        run: pip install Beautifulsoup4 requests 
      - name: Install dependencies
        run: pip install translate requests 
      - name: Install dependencies
        run: pip install json -i https://pypi.tuna.tsinghua.edu.cn/simple
      - name: Install dependencies
        run: pip install plugins 



      
      - name: Run iptv
        run: python ${{ github.workspace }}/iptvsearch/iptv-m3u-maker-master/python/iptv.py

         
      - name: Commit results
        run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Action"
            if [ -n "$(git status --porcelain)" ]; then
            git add  *.m3u
            git commit -m "Automatic update"
            git push
            else
              echo "No changes detected, skipping commit."
            fi
